// AUTO-GENERATED from json-definitions/v1/tech-record/index.json. Do not edit by hand.

import { z } from "zod";

import { AxleSchema } from "./../axle/index.ignore";
import { VehicleClassSchema } from "./../vehicle-class/index.ignore";
import { BrakeSchema } from "./../brake/index.ignore";
import { DimensionsSchema } from "./../dimensions/index.ignore";
import { ADRDetailsSchema } from "./../adr-details/index.ignore";

export const TechRecordSchema = z.object({
  "bodyType": z.unknown(),
  "manufactureYear": z.number().int(),
  "regnDate": z.string(),
  "ntaNumber": z.string(),
  "conversionRefNo": z.string(),
  "speedLimiterMrk": z.boolean(),
  "tachoExemptMrk": z.boolean(),
  "reasonForCreation": z.string(),
  "statusCode": z.string(),
  "grossKerbWeight": z.number().int(),
  "grossLadenWeight": z.number().int(),
  "noOfAxles": z.number().int(),
  "brakeCode": z.string(),
  "vehicleType": z.string(),
  "euVehicleCategory": z.string(),
  "axles": z.array(AxleSchema),
  "vehicleClass": VehicleClassSchema,
  "vehicleSubclass": z.array(z.string()),
  "vehicleConfiguration": z.string(),
  "recordCompleteness": z.string().optional(),
  "chassisMake": z.string().optional(),
  "chassisModel": z.string().optional(),
  "bodyMake": z.string().optional(),
  "bodyModel": z.string().optional(),
  "vehicleSize": z.string().optional(),
  "coifDate": z.string().optional(),
  "unladenWeight": z.number().int().optional(),
  "grossGbWeight": z.number().int().optional(),
  "grossDesignWeight": z.number().int().optional(),
  "grossUnladenWeight": z.number().int().optional(),
  "seatsLowerDeck": z.number().int().optional(),
  "seatsUpperDeck": z.number().int().optional(),
  "standingCapacity": z.number().int().optional(),
  "speedRestriction": z.number().int().optional(),
  "dispensations": z.string().optional(),
  "remarks": z.string().optional(),
  "brakes": BrakeSchema.optional(),
  "make": z.string().optional(),
  "model": z.string().optional(),
  "functionCode": z.string().optional(),
  "typeUseCode": z.string().optional(),
  "roadFriendly": z.boolean().optional(),
  "drawbarCouplingFitted": z.boolean().optional(),
  "dimensions": DimensionsSchema.optional(),
  "notes": z.string(),
  "adrDetails": ADRDetailsSchema.optional(),
  "trainGbWeight": z.number().int().optional(),
  "trainDesignWeight": z.number().int().optional(),
  "maxTrainGbWeight": z.number().int().optional(),
  "maxTrainDesignWeight": z.number().int().optional(),
  "euroStandard": z.number().int().optional(),
  "frontAxleTo5thWheelMin": z.number().int().optional(),
  "frontAxleTo5thWheelMax": z.number().int().optional(),
  "frontAxleTo5thWheelCouplingMin": z.number().int().optional(),
  "frontAxleTo5thWheelCouplingMax": z.number().int().optional(),
  "firstUseDate": z.string().optional(),
  "maxLoadOnCoupling": z.number().int().optional(),
  "suspensionType": z.string().optional(),
  "couplingType": z.string().optional(),
  "frontAxleToRearAxle": z.number().int().optional(),
  "rearAxleToRearTrl": z.number().int().optional(),
  "couplingCenterToRearAxleMin": z.number().int().optional(),
  "couplingCenterToRearAxleMax": z.number().int().optional(),
  "couplingCenterToRearTrlMin": z.number().int().optional(),
  "couplingCenterToRearTrlMax": z.number().int().optional(),
  "numberOfWheelsDriven": z.number().int().optional(),
}).strict();

export type TechRecordSchema = z.infer<typeof TechRecordSchema>;
