// AUTO-GENERATED from json-definitions/v3/tech-record/put/psv/complete/index.json. Do not edit by hand.

import { z } from "zod";

import { StatusCodeSchema } from "./../../../enums/statusCode.ignore";
import { VehicleConfigurationSchema } from "./../../../enums/vehicleConfigurationHgvPsv.enum";
import { VehicleSizeSchema } from "./../../../enums/vehicleSize.ignore";
import { VehicleClassDescriptionSchema } from "./../../../enums/vehicleClassDescriptionPSV.enum";
import { EUvehiclecategorySchema } from "./../../../enums/euVehicleCategoryPsv.enum";
import { ApprovalTypeSchema } from "./../../../enums/approvalTypeHgvOrPsv.enum";
import { BodyTypeDescriptionSchema } from "./../../../enums/bodyTypeDescription.ignore";
import { EurostandardSchema } from "./../../../enums/euroStandard.ignore";
import { FuelPropulsionSystemSchema } from "./../../../enums/fuelPropulsionSystem.ignore";
import { FitmentCodeSchema } from "./../../../enums/fitmentCode.ignore";
import { SpeedCategorySymbolSchema } from "./../../../enums/speedCategorySymbol.ignore";
import { RetarderBrakeSchema } from "./../../../enums/retarderBrake.ignore";
import { MicrofilmDocumentTypeSchema } from "./../../../enums/microfilmDocumentType.ignore";

export const TechRecordPUTPSVCompleteSchema = z.object({
  "vin": z.string(),
  "partialVin": z.string().nullable().optional(),
  "systemNumber": z.string().nullable().optional(),
  "primaryVrm": z.string().nullable().optional(),
  "techRecord_vehicleType": z.literal("psv"),
  "techRecord_statusCode": StatusCodeSchema,
  "techRecord_reasonForCreation": z.string(),
  "techRecord_vehicleConfiguration": VehicleConfigurationSchema,
  "techRecord_vehicleSize": VehicleSizeSchema,
  "techRecord_seatsLowerDeck": z.number().int(),
  "techRecord_seatsUpperDeck": z.number().int(),
  "techRecord_vehicleClass_description": VehicleClassDescriptionSchema,
  "techRecord_hiddenInVta": z.boolean().nullable().optional(),
  "techRecord_recordCompleteness": z.string().nullable().optional(),
  "techRecord_euVehicleCategory": z.union([EUvehiclecategorySchema, z.null()]).optional(),
  "techRecord_regnDate": z.string().regex(new RegExp("^\\d{4}-\\d{2}-\\d{2}$")).nullable().optional(),
  "techRecord_manufactureYear": z.union([z.number().int(), z.null()]).optional(),
  "techRecord_noOfAxles": z.number().int(),
  "techRecord_departmentalVehicleMarker": z.boolean().nullable().optional(),
  "techRecord_alterationMarker": z.boolean().nullable().optional(),
  "techRecord_approvalType": z.union([ApprovalTypeSchema, z.null()]).optional(),
  "techRecord_approvalTypeNumber": z.string().nullable().optional(),
  "techRecord_ntaNumber": z.string().nullable().optional(),
  "techRecord_variantNumber": z.string().nullable().optional(),
  "techRecord_variantVersionNumber": z.string().nullable().optional(),
  "techRecord_bodyType_description": z.union([z.null(), BodyTypeDescriptionSchema]).optional(),
  "techRecord_bodyType_code": z.string().nullable().optional(),
  "techRecord_functionCode": z.string().nullable().optional(),
  "techRecord_conversionRefNo": z.string().nullable().optional(),
  "techRecord_grossGbWeight": z.number().int().nullable().optional(),
  "techRecord_grossDesignWeight": z.number().int().nullable().optional(),
  "techRecord_dda_certificateIssued": z.boolean().nullable(),
  "techRecord_dda_wheelchairCapacity": z.number().int().nullable().optional(),
  "techRecord_dda_wheelchairFittings": z.string().nullable().optional(),
  "techRecord_dda_wheelchairLiftPresent": z.boolean().nullable().optional(),
  "techRecord_dda_wheelchairLiftInformation": z.string().nullable().optional(),
  "techRecord_dda_wheelchairRampPresent": z.boolean().nullable().optional(),
  "techRecord_dda_wheelchairRampInformation": z.string().nullable().optional(),
  "techRecord_dda_minEmergencyExits": z.number().int().nullable().optional(),
  "techRecord_dda_outswing": z.string().nullable().optional(),
  "techRecord_dda_ddaSchedules": z.string().nullable().optional(),
  "techRecord_dda_seatbeltsFitted": z.number().int().nullable().optional(),
  "techRecord_dda_ddaNotes": z.string().nullable().optional(),
  "techRecord_standingCapacity": z.number().int(),
  "techRecord_speedLimiterMrk": z.boolean().nullable().optional(),
  "techRecord_tachoExemptMrk": z.boolean().nullable().optional(),
  "techRecord_euroStandard": z.union([z.null(), EurostandardSchema]).optional(),
  "techRecord_fuelPropulsionSystem": z.union([z.null(), FuelPropulsionSystemSchema]).optional(),
  "techRecord_emissionsLimit": z.number().nullable().optional(),
  "techRecord_trainDesignWeight": z.number().int().nullable().optional(),
  "techRecord_numberOfSeatbelts": z.string(),
  "techRecord_seatbeltInstallationApprovalDate": z.string().nullable().optional(),
  "techRecord_coifSerialNumber": z.string().nullable().optional(),
  "techRecord_coifCertifierName": z.string().nullable().optional(),
  "techRecord_coifDate": z.union([z.string().regex(new RegExp("^\\d{4}-\\d{2}-\\d{2}$")).nullable(), z.string().regex(new RegExp("^$")).nullable()]).optional(),
  "techRecord_bodyMake": z.string(),
  "techRecord_bodyModel": z.string(),
  "techRecord_chassisMake": z.string(),
  "techRecord_chassisModel": z.string(),
  "techRecord_modelLiteral": z.string().nullable().optional(),
  "techRecord_speedRestriction": z.number().nullable().optional(),
  "techRecord_grossKerbWeight": z.number(),
  "techRecord_grossLadenWeight": z.number(),
  "techRecord_unladenWeight": z.number().nullable().optional(),
  "techRecord_maxTrainGbWeight": z.number().nullable().optional(),
  "techRecord_dimensions_length": z.number().int().nullable().optional(),
  "techRecord_dimensions_width": z.number().int().nullable().optional(),
  "techRecord_dimensions_height": z.number().int().nullable().optional(),
  "techRecord_frontAxleToRearAxle": z.number().int().nullable().optional(),
  "techRecord_remarks": z.string().nullable().optional(),
  "techRecord_dispensations": z.string().nullable().optional(),
  "techRecord_axles": z.array(z.object({
  "parkingBrakeMrk": z.boolean(),
  "axleNumber": z.number().int(),
  "weights_gbWeight": z.number().int(),
  "weights_designWeight": z.number().int(),
  "weights_ladenWeight": z.number().int(),
  "weights_kerbWeight": z.number().int(),
  "tyres_tyreCode": z.number().int(),
  "tyres_tyreSize": z.string(),
  "tyres_plyRating": z.string().nullable().optional(),
  "tyres_fitmentCode": FitmentCodeSchema,
  "tyres_dataTrAxles": z.number().int().nullable().optional(),
  "tyres_speedCategorySymbol": SpeedCategorySymbolSchema,
}).strict()),
  "techRecord_applicantDetails_name": z.string().nullable().optional(),
  "techRecord_applicantDetails_address1": z.string().nullable().optional(),
  "techRecord_applicantDetails_address2": z.string().nullable().optional(),
  "techRecord_applicantDetails_postTown": z.string().nullable().optional(),
  "techRecord_applicantDetails_address3": z.string().nullable().optional(),
  "techRecord_applicantDetails_postCode": z.string().nullable().optional(),
  "techRecord_applicantDetails_telephoneNumber": z.string().nullable().optional(),
  "techRecord_applicantDetails_emailAddress": z.string().nullable().optional(),
  "techRecord_brakes_dtpNumber": z.string().nullable().optional(),
  "techRecord_brakes_brakeCode": z.string(),
  "techRecord_brakes_brakeCodeOriginal": z.string().nullable().optional(),
  "techRecord_brakes_dataTrBrakeOne": z.string(),
  "techRecord_brakes_dataTrBrakeTwo": z.string(),
  "techRecord_brakes_dataTrBrakeThree": z.string(),
  "techRecord_brakes_retarderBrakeOne": z.union([RetarderBrakeSchema, z.null()]).optional(),
  "techRecord_brakes_retarderBrakeTwo": z.union([RetarderBrakeSchema, z.null()]).optional(),
  "techRecord_brakes_brakeForceWheelsNotLocked_parkingBrakeForceA": z.number().int(),
  "techRecord_brakes_brakeForceWheelsNotLocked_secondaryBrakeForceA": z.number().int(),
  "techRecord_brakes_brakeForceWheelsNotLocked_serviceBrakeForceA": z.number().int(),
  "techRecord_brakes_brakeForceWheelsUpToHalfLocked_parkingBrakeForceB": z.number().int(),
  "techRecord_brakes_brakeForceWheelsUpToHalfLocked_secondaryBrakeForceB": z.number().int(),
  "techRecord_brakes_brakeForceWheelsUpToHalfLocked_serviceBrakeForceB": z.number().int(),
  "techRecord_microfilm_microfilmDocumentType": z.union([MicrofilmDocumentTypeSchema, z.null()]).optional(),
  "techRecord_microfilm_microfilmRollNumber": z.string().nullable().optional(),
  "techRecord_microfilm_microfilmSerialNumber": z.string().nullable().optional(),
  "techRecord_brakeCode": z.string().nullable().optional(),
  "secondaryVrms": z.array(z.string()).nullable().optional(),
  "techRecord_updateType": z.string().nullable().optional(),
  "techRecord_applicationId": z.string().nullable().optional(),
}).strict();

export type TechRecordPUTPSVComplete = z.infer<typeof TechRecordPUTPSVCompleteSchema>;
