export const schemas = [
  "iva/defects/get/index.json",
  "v1/activity/index.json",
  "v1/defect-category-reference-data/index.json",
  "v1/defect-details/index.json",
  "v1/defect-location/index.json",
  "v1/reason-item/index.json",
  "v1/tech-record/index.json",
  "v1/test/index.json",
  "v1/test-result/index.json",
  "v1/test-station/index.json",
  "v1/test-type/index.json",
  "v1/vehicle/index.json",
  "v1/vehicle-tech-record/index.json",
  "v1/visit/index.json",
  "v3/tech-record/enums/adrAdditionalNotesNumber.enum.json",
  "v3/tech-record/enums/adrBodyType.enum.json",
  "v3/tech-record/enums/adrCompatibilityGroupJ.enum.json",
  "v3/tech-record/enums/adrDangerousGood.enum.json",
  "v3/tech-record/enums/approvalType.enum.json",
  "v3/tech-record/enums/approvalTypeHgvOrPsv.enum.json",
  "v3/tech-record/enums/euVehicleCategory.enum.json",
  "v3/tech-record/enums/euVehicleCategoryHgv.enum.json",
  "v3/tech-record/enums/euVehicleCategoryPsv.enum.json",
  "v3/tech-record/enums/tyreUseCodeHgv.enum.json",
  "v3/tech-record/enums/tyreUseCodeTrl.enum.json",
  "v3/tech-record/enums/vehicleClassDescription.enum.json",
  "v3/tech-record/enums/vehicleClassDescriptionPSV.enum.json",
  "v3/tech-record/enums/vehicleConfigurationHgvPsv.enum.json",
  "v3/tech-record/enums/vehicleConfigurationLightVehicle.enum.json",
  "v3/tech-record/enums/vehicleConfigurationTrl.enum.json",
  "v3/tech-record/get/car/complete/index.json",
  "v3/tech-record/get/car/skeleton/index.json",
  "v3/tech-record/get/hgv/complete/index.json",
  "v3/tech-record/get/hgv/skeleton/index.json",
  "v3/tech-record/get/hgv/testable/index.json",
  "v3/tech-record/get/lgv/complete/index.json",
  "v3/tech-record/get/lgv/skeleton/index.json",
  "v3/tech-record/get/motorcycle/complete/index.json",
  "v3/tech-record/get/motorcycle/skeleton/index.json",
  "v3/tech-record/get/psv/complete/index.json",
  "v3/tech-record/get/psv/skeleton/index.json",
  "v3/tech-record/get/psv/testable/index.json",
  "v3/tech-record/get/search/index.json",
  "v3/tech-record/get/small trl/complete/index.json",
  "v3/tech-record/get/small trl/skeleton/index.json",
  "v3/tech-record/get/trl/complete/index.json",
  "v3/tech-record/get/trl/skeleton/index.json",
  "v3/tech-record/get/trl/testable/index.json",
  "v3/tech-record/put/car/complete/index.json",
  "v3/tech-record/put/car/skeleton/index.json",
  "v3/tech-record/put/hgv/complete/index.json",
  "v3/tech-record/put/hgv/skeleton/index.json",
  "v3/tech-record/put/hgv/testable/index.json",
  "v3/tech-record/put/lgv/complete/index.json",
  "v3/tech-record/put/lgv/skeleton/index.json",
  "v3/tech-record/put/motorcycle/complete/index.json",
  "v3/tech-record/put/motorcycle/skeleton/index.json",
  "v3/tech-record/put/psv/complete/index.json",
  "v3/tech-record/put/psv/skeleton/index.json",
  "v3/tech-record/put/psv/testable/index.json",
  "v3/tech-record/put/small trl/complete/index.json",
  "v3/tech-record/put/small trl/skeleton/index.json",
  "v3/tech-record/put/trl/complete/index.json",
  "v3/tech-record/put/trl/skeleton/index.json",
  "v3/tech-record/put/trl/testable/index.json",
] as const;
