/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Defect Details Schema
 */
export interface Index {
  imNumber?: number;
  imDescription?: string;
  additionalInformation?: string;
  [k: string]: unknown;
}
