/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LoadStatusSchema {
  loadStatus: LoadStatusType;
  unladenBodyType?: UnladenBodyType;
  unladenBodyTypeOtherReason?: string | null;
  reasonForNotLoading?: ReasonForNotLoading;
  otherReasonForNotLoading?: string | null;
  partiallyLadenReason?: string | null;
}

export enum LoadStatusType {
  UNLADEN = "Unladen",
  PARTIALLY_LADEN = "Partially laden",
  PARTIALLY_LADEN_50_TO_65 = "Partially laden 50% to 65%",
  FULLY_LADEN = "Fully laden",
  LOAD_SIMULATED_PARTIALLY_LADEN = "Load simulated partially laden",
  LOAD_SIMULATED_FULLY_LADEN = "Load simulated fully laden"
}
export enum UnladenBodyType {
  SKELETAL = "Skeletal",
  CURTAIN = "Curtain",
  FRIDGE = "Fridge",
  BOX = "Box",
  TANK = "Tank",
  FLAT = "Flat",
  CAR_TRANSPORTER = "Car transporter",
  FIXED_PLANT = "Fixed plant",
  TIPPER = "Tipper",
  REFUGE = "Refuge",
  STREET_CLEANER = "Street cleaner",
  SPECIALISED_VEHICLE_TRAILER = "Specialised vehicle/trailer",
  OTHER = "Other"
}
export enum ReasonForNotLoading {
  OBNOXIOUS_LOADS = "Obnoxious loads",
  TANKER = "Tanker",
  PERISHABLE_GOODS = "Perishable goods",
  LIVESTOCK = "Livestock",
  CAR_TRANSPORTER = "Car transporter",
  REFUGE = "Refuge",
  STREET_CLEANER = "Street cleaner",
  ULTAST = "ULTAST",
  SPECIALIST_BODY_LOAD = "Specialist body/load",
  OTHER = "Other"
}
