/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StatusCode = "provisional" | "current" | "archived";
export type VehicleSize = "small" | "large";
export type BodyTypeDescription =
  | "artic"
  | "articulated"
  | "box"
  | "car transporter"
  | "concrete mixer"
  | "curtainsider"
  | "double decker"
  | "flat"
  | "livestock carrier"
  | "low loader"
  | "mini bus"
  | "other"
  | "other tanker"
  | "petrol/oil tanker"
  | "refrigerated"
  | "refuse"
  | "single decker"
  | "skeletal"
  | "skip loader"
  | "tipper"
  | "tractor";
export type EuroStandard =
  | "0.10 g/kWh Euro 3 PM"
  | "0.03 g/kWh Euro IV PM"
  | "Euro 3"
  | "Euro 4"
  | "Euro 5"
  | "Euro 6"
  | "Euro V"
  | "Euro VI"
  | "Full Electric";
export type FuelPropulsionSystem =
  | "DieselPetrol"
  | "Diesel"
  | "Petrol"
  | "Hybrid"
  | "Electric"
  | "CNG"
  | "Fuel cell"
  | "LNG"
  | "Other";
export type FitmentCode = "single" | "double";
export type SpeedCategorySymbol =
  | "a7"
  | "a8"
  | "b"
  | "c"
  | "d"
  | "e"
  | "f"
  | "g"
  | "j"
  | "k"
  | "l"
  | "m"
  | "n"
  | "p"
  | "q";
export type RetarderBrake = "electric" | "exhaust" | "friction" | "hydraulic" | "other" | "none";
export type MicrofilmDocumentType =
  | "PSV Miscellaneous"
  | "AAT - Trailer Annual Test"
  | "AIV - HGV International App"
  | "COIF Modification"
  | "Trailer COC + Int Plate"
  | "RCT - Trailer Test Cert paid"
  | "HGV COC + Int Plate"
  | "PSV Carry/Auth"
  | "OMO Report"
  | "AIT - Trailer International App"
  | "IPV - HGV EEC Plate/Cert"
  | "XCV - HGV Test Cert free"
  | "AAV - HGV Annual Test"
  | "COIF Master"
  | "Tempo 100 Sp Ord"
  | "Deleted"
  | "PSV N/ALT"
  | "XPT - Tr Plating Cert paid"
  | "FFV - HGV First Test"
  | "Repl Vitesse 100"
  | "TCV - HGV Test Cert"
  | "ZZZ - Miscellaneous"
  | "Test Certificate"
  | "XCT - Trailer Test Cert free"
  | "C52 - COC and VTG52A"
  | "Tempo 100 Report"
  | "Main File Amendment"
  | "PSV Doc"
  | "PSV COC"
  | "PSV Repl COC"
  | "TAV - COC"
  | "NPT - Trailer Alteration"
  | "OMO Certificate"
  | "PSV Repl COIF"
  | "PSV Repl COF"
  | "COIF Application"
  | "XPV - HGV Plating Cert Free"
  | "TCT - Trailer Test Cert"
  | "Tempo 100 App"
  | "PSV Decision on N/ALT"
  | "Special Order PSV"
  | "NPV - HGV Alteration"
  | "No Description Found"
  | "Vitesse 100 Sp Ord"
  | "Brake Test Details"
  | "COIF Productional"
  | "RDT - Test Disc Paid"
  | "RCV - HGV Test Cert"
  | "FFT - Trailer First Test"
  | "IPT - Trailer EEC Plate/Cert"
  | "XDT - Test Disc Free"
  | "PRV - HGV Plating Cert paid"
  | "COF Cert"
  | "PRT - Tr Plating Cert paid"
  | "Tempo 100 Permit";

export interface TechRecordPUTPSVComplete {
  vin: string;
  partialVin?: string | null;
  systemNumber?: null | string;
  primaryVrm?: null | string;
  techRecord_vehicleType: "psv";
  techRecord_statusCode: StatusCode;
  techRecord_reasonForCreation: string;
  techRecord_vehicleConfiguration: VehicleConfiguration;
  techRecord_vehicleSize: VehicleSize;
  techRecord_seatsLowerDeck: number;
  techRecord_seatsUpperDeck: number;
  techRecord_vehicleClass_description: VehicleClassDescription;
  techRecord_hiddenInVta?: null | boolean;
  techRecord_recordCompleteness?: null | string;
  techRecord_euVehicleCategory?: EUVehicleCategory | null;
  techRecord_regnDate?: null | string;
  techRecord_manufactureYear?: number | null;
  techRecord_noOfAxles: number;
  techRecord_departmentalVehicleMarker?: boolean | null;
  techRecord_alterationMarker?: boolean | null;
  techRecord_approvalType?: ApprovalType | null;
  techRecord_approvalTypeNumber?: string | null;
  techRecord_ntaNumber?: string | null;
  techRecord_variantNumber?: string | null;
  techRecord_variantVersionNumber?: string | null;
  techRecord_bodyType_description?: null | BodyTypeDescription;
  techRecord_bodyType_code?: null | string;
  techRecord_functionCode?: string | null;
  techRecord_conversionRefNo?: string | null;
  techRecord_grossGbWeight?: number | null;
  techRecord_grossDesignWeight?: number | null;
  techRecord_dda_certificateIssued: boolean | null;
  techRecord_dda_wheelchairCapacity?: number | null;
  techRecord_dda_wheelchairFittings?: string | null;
  techRecord_dda_wheelchairLiftPresent?: boolean | null;
  techRecord_dda_wheelchairLiftInformation?: string | null;
  techRecord_dda_wheelchairRampPresent?: boolean | null;
  techRecord_dda_wheelchairRampInformation?: string | null;
  techRecord_dda_minEmergencyExits?: number | null;
  techRecord_dda_outswing?: string | null;
  techRecord_dda_ddaSchedules?: string | null;
  techRecord_dda_seatbeltsFitted?: number | null;
  techRecord_dda_ddaNotes?: string | null;
  techRecord_standingCapacity: number;
  techRecord_speedLimiterMrk?: null | boolean;
  techRecord_tachoExemptMrk?: null | boolean;
  techRecord_euroStandard?: null | EuroStandard;
  techRecord_fuelPropulsionSystem?: null | FuelPropulsionSystem;
  techRecord_emissionsLimit?: null | {
    [k: string]: unknown;
  };
  techRecord_trainDesignWeight?: number | null;
  techRecord_numberOfSeatbelts: string;
  techRecord_seatbeltInstallationApprovalDate?: string | null;
  techRecord_coifSerialNumber?: string | null;
  techRecord_coifCertifierName?: string | null;
  techRecord_coifDate?: string | null;
  techRecord_bodyMake: string;
  techRecord_bodyModel: string;
  techRecord_chassisMake: string;
  techRecord_chassisModel: string;
  techRecord_modelLiteral?: string | null;
  techRecord_speedRestriction?: number | null;
  techRecord_grossKerbWeight: number;
  techRecord_grossLadenWeight: number;
  techRecord_unladenWeight?: number | null;
  techRecord_maxTrainGbWeight?: number | null;
  techRecord_dimensions_length?: number | null;
  techRecord_dimensions_width?: number | null;
  techRecord_dimensions_height?: number | null;
  techRecord_frontAxleToRearAxle?: number | null;
  techRecord_remarks?: string | null;
  techRecord_dispensations?: string | null;
  /**
   * @minItems 1
   */
  techRecord_axles: [PSVAxlesComplete, ...PSVAxlesComplete[]];
  techRecord_applicantDetails_name?: string | null;
  techRecord_applicantDetails_address1?: null | string;
  techRecord_applicantDetails_address2?: null | string;
  techRecord_applicantDetails_postTown?: null | string;
  techRecord_applicantDetails_address3?: null | string;
  techRecord_applicantDetails_postCode?: null | string;
  techRecord_applicantDetails_telephoneNumber?: null | string;
  techRecord_applicantDetails_emailAddress?: null | string;
  techRecord_brakes_dtpNumber?: string | null;
  techRecord_brakes_brakeCode: string;
  techRecord_brakes_brakeCodeOriginal?: string | null;
  techRecord_brakes_dataTrBrakeOne: string;
  techRecord_brakes_dataTrBrakeTwo: string;
  techRecord_brakes_dataTrBrakeThree: string;
  techRecord_brakes_retarderBrakeOne?: RetarderBrake | null;
  techRecord_brakes_retarderBrakeTwo?: RetarderBrake | null;
  techRecord_brakes_brakeForceWheelsNotLocked_parkingBrakeForceA: number;
  techRecord_brakes_brakeForceWheelsNotLocked_secondaryBrakeForceA: number;
  techRecord_brakes_brakeForceWheelsNotLocked_serviceBrakeForceA: number;
  techRecord_brakes_brakeForceWheelsUpToHalfLocked_parkingBrakeForceB: number;
  techRecord_brakes_brakeForceWheelsUpToHalfLocked_secondaryBrakeForceB: number;
  techRecord_brakes_brakeForceWheelsUpToHalfLocked_serviceBrakeForceB: number;
  techRecord_microfilm_microfilmDocumentType?: MicrofilmDocumentType | null;
  techRecord_microfilm_microfilmRollNumber?: string | null;
  techRecord_microfilm_microfilmSerialNumber?: string | null;
  techRecord_brakeCode?: string | null;
  secondaryVrms?: null | string[];
  techRecord_updateType?: null | string;
  techRecord_applicationId?: null | string;
}
export interface PSVAxlesComplete {
  parkingBrakeMrk: boolean;
  axleNumber: number;
  weights_gbWeight: number;
  weights_designWeight: number;
  weights_ladenWeight: number;
  weights_kerbWeight: number;
  tyres_tyreCode: number;
  tyres_tyreSize: string;
  tyres_plyRating?: string | null;
  tyres_fitmentCode: FitmentCode;
  tyres_dataTrAxles?: null | number;
  tyres_speedCategorySymbol: SpeedCategorySymbol;
}

export enum VehicleConfiguration {
  RIGID = "rigid",
  ARTICULATED = "articulated"
}
export enum VehicleClassDescription {
  SMALL_PSV = "small psv (ie: less than or equal to 22 seats)",
  LARGE_PSV = "large psv(ie: greater than 23 seats)"
}
export enum EUVehicleCategory {
  M1 = "m1",
  M2 = "m2",
  M3 = "m3"
}
export enum ApprovalType {
  NTA = "NTA",
  ECTA = "ECTA",
  IVA = "IVA",
  NSSTA = "NSSTA",
  ECSSTA = "ECSSTA",
  GB_WVTA = "GB WVTA",
  PROV_GB_WVTA = "Prov.GB WVTA",
  SMALL_SERIES_NKSXX = "Small series NKSXX",
  SMALL_SERIES_NKS = "Small series NKS",
  IVA_VCA = "IVA - VCA",
  IVA_DVSA_NI = "IVA - DVSA/NI"
}
