export {
    techRecordV3Schema, type TechRecordV3,
    techRecordV1Schema, type TechRecordV1,
    bodyTypeSchema, type BodyType,
    vehicleClassSchema, type VehicleClass,
    dimensionsSchema, type Dimensions,
    weightsSchema, type Weights,
    tyresSchema, type Tyres,
    axleSchema, type Axle,
    plateSchema, type Plate,
    applicantDetailsSchema, type ApplicantDetails,
    microfilmSchema, type Microfilm,
    ddaSchema, type DDA,
    adrTc3DetailSchema, type AdrTc3Detail,
    adrPassCertificateSchema, type AdrPassCertificate,
    adrExaminerNoteSchema, type AdrExaminerNote,
    adrDetailsSchema, type AdrDetails,
    contactDetailsSchema,
    purchaserDetailsSchema, type PurchaserDetails,
    manufacturerDetailsSchema, type ManufacturerDetails,
    authIntoServiceSchema, type AuthIntoService,
    letterOfAuthSchema, type LetterOfAuth,
} from '../../types/v3/tech-record';
