/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type VehicleConfiguration =
  | "rigid"
  | "articulated"
  | "centre axle drawbar"
  | "semi-car transporter"
  | "semi-trailer"
  | "long semi-trailer"
  | "low loader"
  | "other"
  | "drawbar"
  | "four-in-line"
  | "dolly"
  | "full drawbar";
export type VehicleSize = "small" | "large";

export interface PSVTechnicalRecordV3Skeleton {
  vin: string;
  systemNumber: string;
  primaryVrm: string;
  vehicleType: "psv";
  techRecord_vehicleConfiguration: VehicleConfiguration;
  techRecord_vehicleSize: VehicleSize;
  techRecord_seatsLowerDeck: number;
  techRecord_seatsUpperDeck: number;
  techRecord_numberOfWheelsDriven: string | null;
}
