/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ActivitySchema {
  parentId?: string;
  id?: string;
  activityType: ActivityType;
  testStationName: string;
  testStationPNumber: string;
  testStationEmail: string;
  testStationType: TestStationType;
  testerName: string;
  testerStaffId: string;
  testerEmail?: string;
  startTime: string;
  endTime?: string;
  waitReason?: string[];
  notes?: string;
  activityDay?: string;
}

export enum ActivityType {
  VISIT = "visit",
  WAIT = "time",
  UNACCOUNTABLE_TIME = "unaccountable time"
}
export enum TestStationType {
  ATF = "atf",
  GVTS = "gvts",
  HQ = "hq",
  POTF = "potf"
}
