/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export const HazardClassification = {
  _1: {code: "1", description: "Explosive"},
  _2: {code: "2", description: "Compressed Gases"},
  _3: {code: "3", description: "Flammable liquids"},
  "_4.1": {code: "4.1", description: "Flammable solids"},
  "_4.2": {code: "4.2", description: "Spontaneously combustible"},
  "_4.3": {code: "4.3", description: "Dangerous when wet"},
  "_5.1": {code: "5.1", description: "Oxidising agents"},
  "_5.2": {code: "5.2", description: "Organic peroxides"},
  "_6.1": {code: "6.1", description: "Toxics"},
  "_6.2": {code: "6.2", description: "Infectious substances"},
  _7: {code: "7", description: "Radioactive"},
  _8: {code: "8", description: "Corrosives"},
  _9: {code: "9", description: "Miscellaneous"}
} as const;

export type HazardClassification = (typeof HazardClassification)[keyof typeof HazardClassification];
