/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum HazardClassification {
  _1 = "1",
  _2 = "2",
  _3 = "3",
  "4.1" = "4.1",
  "4.2" = "4.2",
  "4.3" = "4.3",
  "5.1" = "5.1",
  "5.2" = "5.2",
  "6.1" = "6.1",
  "6.2" = "6.2",
  _7 = "7",
  _8 = "8",
  _9 = "9"
}
