/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum ModTypeDescription {
  PARTICULATE_TRAP = "particulate trap",
  MODIFICATION_OR_CHANGE_OF_ENGINE = "modification or change of engine",
  GAS_ENGINE = "gas engine"
}
