/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum VehicleClassCode {
  _1 = "1",
  _2 = "2",
  _3 = "3",
  N = "n",
  S = "s",
  T = "t",
  L = "l",
  V = "v",
  _4 = "4",
  _5 = "5",
  _7 = "7",
  P = "p",
  U = "u"
}
