/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum VehicleSubclass {
  A = "a",
  C = "c",
  S = "s",
  L = "l",
  M = "m",
  N = "n",
  P = "p",
  T = "t",
  R = "r"
}
