/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DefectCategoryReferenceDataSchema {
  imNumber: number;
  imDescription: string;
  forVehicleType: string[];
  additionalInfo: AdditionalInfoSchema;
  items: DefectDeficiencyReferenceDataSchema;
}
export interface AdditionalInfoSchema {
  psv: {
    location?: DefectLocationSchema;
    notes?: string;
  };
  hgv: {
    location?: DefectLocationSchema;
    notes?: string;
  };
  trl: {
    location?: DefectLocationSchema;
    notes?: string;
  };
}
export interface DefectLocationSchema {
  vertical?: string | null;
  horizontal?: string | null;
  lateral?: string | null;
  longitudinal?: string | null;
  rowNumber?: number | null;
  seatNumber?: number | null;
  axleNumber?: number | null;
}
export interface DefectDeficiencyReferenceDataSchema {
  ref: string;
  deficiencyId: string | null;
  deficiencySubId: string;
  deficiencyCategory: string;
  deficiencyText: string;
  stdForProhibition: string;
  forVehicleType: string;
}
