/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MediaSchema = ImageSchema | VideoSchema | FailReasonSchema;

export interface ImageSchema {
  type: "image";
  path: string;
}
export interface VideoSchema {
  type: "video";
  path: string;
}
export interface FailReasonSchema {
  type: "failReason";
  path: string;
  reason: string;
}
