/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MediaSchema {
  fileType: FileType;
  filePath: string;
  duration?: number | null;
  width?: number | null;
  height?: number | null;
  failReason?: string | null;
}

export enum FileType {
  VIDEO = "Video",
  IMAGE = "Image"
}
