/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DefectDeficiencyReferenceDataSchema {
  ref: string;
  deficiencyId: string | null;
  deficiencySubId: string;
  deficiencyCategory: string;
  deficiencyText: string;
  stdForProhibition: boolean;
  forVehicleType: string[] | ("psv" | "hgv" | "trl" | "car" | "lgv" | "motorcycle");
}
