/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GETTestTypeSchema {
  typeOfTest?: string;
  id: string;
  sortId: string;
  linkedIds: string[] | null;
  suggestedTestTypeIds?: string[];
  name: string;
  testTypeName?: string;
  suggestedTestTypeDisplayName?: string;
  suggestedTestTypeDisplayOrder?: string;
  forVehicleType: VehicleType[];
  forProvisionalStatus?: boolean;
  forProvisionalStatusOnly?: boolean;
  forVehicleSize: VehicleSize[] | null;
  forVehicleConfiguration: VehicleConfiguration[] | null;
  forVehicleAxles: number[] | null;
  forEuVehicleCategory: EUVehicleCategory[] | null;
  forVehicleClass: string[] | null;
  forVehicleSubclass: VehicleSubclass[] | null;
  forVehicleWheels: number[] | null;
  testTypeClassification?: TestTypeClassification;
  testCodes?: TestCodeSchema[];
  nextTestTypesOrCategories?: NextTestTypesOrCategorySchema[];
}
export interface TestCodeSchema {
  forVehicleType: VehicleType | VehicleType[];
  forVehicleSize: VehicleSize | null;
  forVehicleConfiguration: VehicleConfiguration | null;
  forVehicleAxles: number | number[] | null;
  forEuVehicleCategory: EUVehicleCategory | EUVehicleCategory[] | null;
  forVehicleClass: string | string[] | null;
  forVehicleSubclass: VehicleSubclass | VehicleSubclass[] | null;
  forVehicleWheels: number | number[] | null;
  defaultTestCode: string;
  linkedTestCode: string | null;
  forProvisionalStatus?: boolean;
  forProvisionalStatusOnly?: boolean;
}
export interface NextTestTypesOrCategorySchema {
  typeOfTest?: string;
  id: string;
  linkedIds: string[] | null;
  name: string;
  testTypeName?: string;
  forVehicleType: VehicleType | VehicleType[];
  forProvisionalStatus?: boolean;
  forProvisionalStatusOnly?: boolean;
  forVehicleSize: VehicleSize[] | null;
  forVehicleConfiguration: VehicleConfiguration[] | null;
  forVehicleAxles: number[] | null;
  forEuVehicleCategory: EUVehicleCategory[] | null;
  forVehicleClass: string[] | null;
  forVehicleSubclass: VehicleSubclass[] | null;
  forVehicleWheels: number[] | null;
  testTypeClassification?: TestTypeClassification;
  testCodes?: TestCodeSchema[];
  nextTestTypesOrCategories?: NextTestTypesOrCategorySchema[];
}

export enum VehicleType {
  HGV = "hgv",
  PSV = "psv",
  TRL = "trl",
  LGV = "lgv",
  CAR = "car",
  MOTORCYCLE = "motorcycle"
}
export enum VehicleSize {
  LARGE = "large",
  SMALL = "small"
}
export enum VehicleConfiguration {
  RIGID = "rigid",
  ARTICULATED = "articulated",
  CENTRE_AXLE_DRAWBAR = "centre axle drawbar",
  SEMI_CAR_TRANSPORTER = "semi-car transporter",
  SEMI_TRAILER = "semi-trailer",
  LONG_SEMI_TRAILER = "long semi-trailer",
  LOW_LOADER = "low loader",
  OTHER = "other",
  DRAWBAR = "drawbar",
  FOUR_IN_LINE = "four-in-line",
  DOLLY = "dolly",
  FULL_DRAWBAR = "full drawbar"
}
export enum EUVehicleCategory {
  M1 = "m1",
  M2 = "m2",
  M3 = "m3",
  N1 = "n1",
  N2 = "n2",
  N3 = "n3",
  O1 = "o1",
  O2 = "o2",
  O3 = "o3",
  O4 = "o4",
  L1E_A = "l1e-a",
  L1E = "l1e",
  L2E = "l2e",
  L3E = "l3e",
  L4E = "l4e",
  L5E = "l5e",
  L6E = "l6e",
  L7E = "l7e"
}
export enum VehicleSubclass {
  A = "a",
  C = "c",
  S = "s",
  L = "l",
  M = "m",
  N = "n",
  P = "p",
  T = "t",
  R = "r"
}
export enum TestTypeClassification {
  ANNUAL_NO_CERTIFICATE = "Annual NO CERTIFICATE",
  ANNUAL_WITH_CERTIFICATE = "Annual With Certificate",
  NON_ANNUAL = "NON ANNUAL",
  IVA_WITH_CERTIFICATE = "IVA With Certificate",
  MSVA_WITH_CERTIFICATE = "MSVA With Certificate"
}
