/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum TestTypeClassification {
  ANNUAL_NO_CERTIFICATE = "Annual NO CERTIFICATE",
  ANNUAL_WITH_CERTIFICATE = "Annual With Certificate",
  NON_ANNUAL = "NON ANNUAL",
  IVA_WITH_CERTIFICATE = "IVA With Certificate",
  MSVA_WITH_CERTIFICATE = "MSVA With Certificate"
}
