/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MediaSchema = ImageSchema | VideoSchema | FailReasonSchema;

export interface VTG15Schema {
  vtg15Required: boolean;
  unNumber?: number;
  primaryHazardClassification?: HazardClassification;
  secondaryHazardClassification?: HazardClassification;
  media?: MediaSchema[];
}
export interface ImageSchema {
  type: "image";
  path: string;
}
export interface VideoSchema {
  type: "video";
  path: string;
}
export interface FailReasonSchema {
  type: "failReason";
  path: string;
  reason: string;
}

export declare const HazardClassification: {
  _1: { readonly code: "1"; readonly description: "Explosive"; };
  _2: { readonly code: "2"; readonly description: "Compressed Gases"; };
  _3: { readonly code: "3"; readonly description: "Flammable liquids"; };
  "_4.1": { readonly code: "4.1"; readonly description: "Flammable solids"; };
  "_4.2": { readonly code: "4.2"; readonly description: "Spontaneously combustible"; };
  "_4.3": { readonly code: "4.3"; readonly description: "Dangerous when wet"; };
  "_5.1": { readonly code: "5.1"; readonly description: "Oxidising agents"; };
  "_5.2": { readonly code: "5.2"; readonly description: "Organic peroxides"; };
  "_6.1": { readonly code: "6.1"; readonly description: "Toxics"; };
  "_6.2": { readonly code: "6.2"; readonly description: "Infectious substances"; };
  _7: { readonly code: "7"; readonly description: "Radioactive"; };
  _8: { readonly code: "8"; readonly description: "Corrosives"; };
  _9: { readonly code: "9"; readonly description: "Miscellaneous"; };
};

export type HazardClassification = (typeof HazardClassification)[keyof typeof HazardClassification];
