/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MediaSchema = ImageSchema | VideoSchema | FailReasonSchema;

export interface VTG15Schema {
  vtg15Required: boolean;
  unNumber?: number;
  primaryHazardClassification?: HazardClassification;
  secondaryHazardClassification?: HazardClassification;
  media?: MediaSchema[];
}
export interface ImageSchema {
  type: "image";
  path: string;
}
export interface VideoSchema {
  type: "video";
  path: string;
}
export interface FailReasonSchema {
  type: "failReason";
  path: string;
  reason: string;
}

export enum HazardClassification {
  _1 = "1",
  _2 = "2",
  _3 = "3",
  "_4.1" = "4.1",
  "_4.2" = "4.2",
  "_4.3" = "4.3",
  "_5.1" = "5.1",
  "_5.2" = "5.2",
  "_6.1" = "6.1",
  "_6.2" = "6.2",
  _7 = "7",
  _8 = "8",
  _9 = "9"
}
