/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum ADRAdditionalNotesNumber {
  ONE = "1",
  ONE_A = "1A",
  TWO = "2",
  THREE = "3",
  V1B = "V1B",
  T1B = "T1B"
}
