/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum ADRBodyDeclarationTypes {
  PRE_1_JULY_2005 = "Pre 1st July 2005",
  ON_OR_AFTER_1_JULY_2005 = "On or after 1st July 2005",
  UNKNOWN = "Unknown"
}
