/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum ADRDangerousGood {
  FP = "FP <61 (FL)",
  AT = "AT",
  HYDROGEN_PEROXIDE = "Class 5.1 Hydrogen Peroxide (OX)",
  MEMU = "MEMU",
  CARBON_DISULPHIDE = "Carbon Disulphide",
  HYDROGEN = "Hydrogen",
  EXPLOSIVES_TYPE_2 = "Explosives (type 2)",
  EXPLOSIVES_TYPE_3 = "Explosives (type 3)"
}
