/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum ADRTankStatementSubstancePermitted {
  UNDER_TANK_CODE = "Substances permitted under the tank code and any special provisions specified in 9 may be carried",
  UNDER_UN_NUMBER = "Substances (Class UN number and if necessary packing group and proper shipping name) may be carried"
}
