/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum EUVehicleCategory {
  O1 = "o1",
  O2 = "o2",
  O3 = "o3",
  O4 = "o4"
}
