/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type InspectionType = "basic" | "normal";

export interface DefectGETRequiredStandards {
  euVehicleCategories: EUVehicleCategory[];
  basic: RequiredStandardTaxonomySection[];
  normal: RequiredStandardTaxonomySection[];
}
export interface RequiredStandardTaxonomySection {
  sectionNumber: string;
  sectionDescription: string;
  requiredStandards: RequiredStandard[];
}
export interface RequiredStandard {
  rsNumber: number;
  requiredStandard: string;
  refCalculation: string;
  additionalInfo: boolean;
  inspectionTypes: InspectionType[];
}

export enum EUVehicleCategory {
  M1 = "m1",
  M2 = "m2",
  M3 = "m3",
  N1 = "n1",
  N2 = "n2",
  N3 = "n3",
  O1 = "o1",
  O2 = "o2",
  O3 = "o3",
  O4 = "o4",
  L1E_A = "l1e-a",
  L1E = "l1e",
  L2E = "l2e",
  L3E = "l3e",
  L4E = "l4e",
  L5E = "l5e",
  L6E = "l6e",
  L7E = "l7e"
}
