/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TechRecordCompleteCarSchema = TechRecordPUTResponseCompleteCarSchema;
export type EUVehicleCategory = string | null;
export type VehicleConfiguration =
  | "rigid"
  | "articulated"
  | "centre axle drawbar"
  | "semi-car transporter"
  | "semi-trailer"
  | "long semi-trailer"
  | "low loader"
  | "other"
  | "drawbar"
  | "four-in-line"
  | "dolly"
  | "full drawbar";
export type StatusCode = "current" | "provisional" | "archived";
export type VehicleType = "psv" | "trl" | "hgv" | "car" | "lgv" | "motorcycle";

export interface TechRecordPUTResponseCompleteCarSchema {
  techRecord_applicantDetails_name?: string | null;
  techRecord_applicantDetails_address1?: null | string;
  techRecord_applicantDetails_address2?: null | string;
  techRecord_applicantDetails_postTown?: null | string;
  techRecord_applicantDetails_address3?: null | string;
  techRecord_applicantDetails_postCode?: null | string;
  techRecord_applicantDetails_telephoneNumber?: null | string;
  techRecord_applicantDetails_emailAddress?: null | string;
  vin?: string;
  systemNumber: string;
  createdTimestamp: string;
  partialVin?: string;
  primaryVrm?: string;
  techRecord_createdAt?: string;
  techRecord_createdByName?: string | null;
  techRecord_createdById?: string | null;
  techRecord_euVehicleCategory?: EUVehicleCategory;
  techRecord_lastUpdatedAt?: string | null;
  techRecord_lastUpdatedByName?: string | null;
  techRecord_lastUpdatedById?: string | null;
  techRecord_recordCompleteness?: "complete" | "testable" | "skeleton";
  techRecord_vehicleConfiguration?: VehicleConfiguration;
  techRecord_noOfAxles?: number | null;
  techRecord_manufactureYear?: number | null;
  techRecord_regnDate?: string | null;
  techRecord_statusCode?: StatusCode;
  techRecord_vehicleType?: VehicleType;
  techRecord_reasonForCreation?: string | null;
  techRecord_bodyType_code?: string;
  techRecord_bodyType_description?: string;
  [k: string]: unknown;
}
