// AUTO-GENERATED from json-definitions/v3/tech-record/get/trl/skeleton/index.json. Do not edit by hand.

import { z } from "zod";

import { ADRBodyDeclarationTypesSchema } from "./../../../enums/adrBodyDeclarationType.enum";
import { RadioButtonOptionsSchema } from "./../../../enums/radioButtonOptions.enum";
import { ADRCompatibilityGroupJSchema } from "./../../../enums/adrCompatibilityGroupJ.enum";
import { TC2TypesSchema } from "./../../../enums/tc2Types.ignore";
import { TC3TypesSchema } from "./../../../enums/tc3Types.enum";
import { ADRTankDetailsTankStatementSelectSchema } from "./../../../enums/adrTankDetailsTankStatementSelect.enum";
import { ADRCertificateTypesSchema } from "./../../../enums/adrCertificateTypes.enum";
import { ApprovalTypeSchema } from "./../../../enums/approvalType.enum";
import { EUvehiclecategorySchema } from "./../../../enums/euVehicleCategoryTrl.enum";
import { FrameDescriptionSchema } from "./../../../enums/frameDescription.ignore";
import { lettertypesSchema } from "./../../../enums/letterType.ignore";
import { ParagraphIdsSchema } from "./../../../enums/paragraphId.ignore";
import { MonthsSchema } from "./../../../enums/manufactureMonth.ignore";
import { MicrofilmDocumentTypeSchema } from "./../../../enums/microfilmDocumentType.ignore";
import { FitmentCodeSchema } from "./../../../enums/fitmentCode.ignore";
import { SpeedCategorySymbolSchema } from "./../../../enums/speedCategorySymbol.ignore";
import { PlateReasonForIssueSchema } from "./../../../enums/plateReasonForIssue.ignore";
import { StatusCodeSchema } from "./../../../enums/statusCode.ignore";
import { TyreUseCodeSchema } from "./../../../enums/tyreUseCodeTrl.enum";
import { VehicleConfigurationSchema } from "./../../../enums/vehicleConfigurationTrl.enum";

export const TechRecordGETTRLSkeletonSchema = z.object({
  "createdTimestamp": z.string(),
  "partialVin": z.string(),
  "systemNumber": z.string(),
  "techRecord_adrDetails_documentId": z.string().optional(),
  "techRecord_adrDetails_dangerousGoods": z.boolean().nullable().optional(),
  "techRecord_adrDetails_vehicleDetails_type": z.string().nullable().optional(),
  "techRecord_adrDetails_bodyDeclaration_type": z.union([z.null(), ADRBodyDeclarationTypesSchema]).optional(),
  "techRecord_adrDetails_vehicleDetails_usedOnInternationalJourneys": z.union([z.null(), RadioButtonOptionsSchema]).optional(),
  "techRecord_adrDetails_vehicleDetails_approvalDate": z.union([z.string().regex(new RegExp("^\\d{4}-\\d{2}-\\d{2}$")), z.null()]).optional(),
  "techRecord_adrDetails_permittedDangerousGoods": z.array(z.string()).nullable().optional(),
  "techRecord_adrDetails_compatibilityGroupJ": z.union([z.null(), ADRCompatibilityGroupJSchema]).optional(),
  "techRecord_adrDetails_additionalExaminerNotes": z.array(z.object({
  "note": z.string().nullable().optional(),
  "createdAtDate": z.string().nullable().optional(),
  "lastUpdatedBy": z.string().nullable().optional(),
}).strict()).nullable().optional(),
  "techRecord_adrDetails_applicantDetails_name": z.string().nullable().optional(),
  "techRecord_adrDetails_applicantDetails_street": z.string().nullable().optional(),
  "techRecord_adrDetails_applicantDetails_town": z.string().nullable().optional(),
  "techRecord_adrDetails_applicantDetails_city": z.string().nullable().optional(),
  "techRecord_adrDetails_applicantDetails_postcode": z.string().nullable().optional(),
  "techRecord_adrDetails_memosApply": z.array(z.string()).nullable().optional(),
  "techRecord_adrDetails_documents": z.array(z.string()).nullable().optional(),
  "techRecord_adrDetails_listStatementApplicable": z.boolean().nullable().optional(),
  "techRecord_adrDetails_batteryListNumber": z.string().nullable().optional(),
  "techRecord_adrDetails_brakeDeclarationsSeen": z.boolean().nullable().optional(),
  "techRecord_adrDetails_brakeDeclarationIssuer": z.string().nullable().optional(),
  "techRecord_adrDetails_brakeEndurance": z.boolean().nullable().optional(),
  "techRecord_adrDetails_weight": z.number().nullable().optional(),
  "techRecord_adrDetails_declarationsSeen": z.boolean().nullable().optional(),
  "techRecord_adrDetails_m145Statement": z.boolean().nullable().optional(),
  "techRecord_adrDetails_newCertificateRequested": z.boolean().nullable().optional(),
  "techRecord_adrDetails_additionalNotes_number": z.array(z.string()).nullable().optional(),
  "techRecord_adrDetails_adrTypeApprovalNo": z.string().nullable().optional(),
  "techRecord_adrDetails_adrCertificateNotes": z.string().nullable().optional(),
  "techRecord_adrDetails_approved": z.boolean().nullable().optional(),
  "techRecord_adrDetails_receivedDate": z.union([z.string().regex(new RegExp("^\\d{4}-\\d{2}-\\d{2}$")), z.null()]).optional(),
  "techRecord_adrDetails_applicationNumber": z.union([z.string().regex(new RegExp("^APP-\\d{7}-\\d{4}-\\d{1,2}$")), z.null()]).optional(),
  "techRecord_adrDetails_tank_tankDetails_tankManufacturer": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_yearOfManufacture": z.number().int().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankManufacturerSerialNo": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankTypeAppNo": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankCode": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_specialProvisions": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tc2Details_tc2Type": z.union([z.null(), TC2TypesSchema]).optional(),
  "techRecord_adrDetails_tank_tankDetails_tc2Details_tc2IntermediateApprovalNo": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tc2Details_tc2IntermediateExpiryDate": z.union([z.string().regex(new RegExp("^\\d{4}-\\d{2}-\\d{2}$")), z.null()]).optional(),
  "techRecord_adrDetails_tank_tankDetails_tc3Details": z.array(z.object({
  "tc3Type": z.union([z.null(), TC3TypesSchema]).optional(),
  "tc3PeriodicNumber": z.string().nullable().optional(),
  "tc3PeriodicExpiryDate": z.union([z.string().regex(new RegExp("^\\d{4}-\\d{2}-\\d{2}$")), z.null()]).optional(),
}).strict()).nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankStatement_substancesPermitted": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankStatement_select": z.union([z.null(), ADRTankDetailsTankStatementSelectSchema]).optional(),
  "techRecord_adrDetails_tank_tankDetails_tankStatement_statement": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankStatement_productListRefNo": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankStatement_productListUnNo": z.array(z.string()).nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankStatement_productList": z.string().nullable().optional(),
  "techRecord_adrPassCertificateDetails": z.array(z.object({
  "createdByName": z.string(),
  "certificateType": ADRCertificateTypesSchema,
  "generatedTimestamp": z.string(),
  "certificateId": z.string(),
}).strict()).nullable().optional(),
  "techRecord_alterationMarker": z.boolean().nullable().optional(),
  "techRecord_applicantDetails_name": z.string().nullable().optional(),
  "techRecord_applicantDetails_address1": z.string().nullable().optional(),
  "techRecord_applicantDetails_address2": z.string().nullable().optional(),
  "techRecord_applicantDetails_postTown": z.string().nullable().optional(),
  "techRecord_applicantDetails_address3": z.string().nullable().optional(),
  "techRecord_applicantDetails_postCode": z.string().nullable().optional(),
  "techRecord_applicantDetails_telephoneNumber": z.string().nullable().optional(),
  "techRecord_applicantDetails_emailAddress": z.string().nullable().optional(),
  "techRecord_applicationId": z.string().nullable().optional(),
  "techRecord_approvalType": z.union([ApprovalTypeSchema, z.null()]).optional(),
  "techRecord_approvalTypeNumber": z.string().nullable().optional(),
  "techRecord_ntaNumber": z.string().nullable().optional(),
  "techRecord_variantNumber": z.string().nullable().optional(),
  "techRecord_variantVersionNumber": z.string().nullable().optional(),
  "techRecord_authIntoService": z.string().nullable().optional(),
  "techRecord_batchId": z.string().nullable().optional(),
  "techRecord_bodyType_code": z.string().nullable(),
  "techRecord_bodyType_description": z.string().nullable(),
  "techRecord_brakes_antilockBrakingSystem": z.boolean().nullable().optional(),
  "techRecord_brakes_dtpNumber": z.string().nullable().optional(),
  "techRecord_brakes_loadSensingValve": z.boolean().nullable().optional(),
  "techRecord_centreOfRearmostAxleToRearOfTrl": z.number().int().nullable().optional(),
  "techRecord_conversionRefNo": z.string().nullable().optional(),
  "techRecord_couplingCenterToRearAxleMax": z.number().int().nullable().optional(),
  "techRecord_couplingCenterToRearAxleMin": z.number().int().nullable().optional(),
  "techRecord_couplingCenterToRearTrlMax": z.number().int().nullable().optional(),
  "techRecord_couplingCenterToRearTrlMin": z.number().int().nullable().optional(),
  "techRecord_couplingType": z.string().nullable().optional(),
  "techRecord_createdAt": z.string(),
  "techRecord_createdById": z.string(),
  "techRecord_createdByName": z.string(),
  "techRecord_departmentalVehicleMarker": z.boolean().nullable().optional(),
  "techRecord_dimensions_length": z.number().int().nullable().optional(),
  "techRecord_dimensions_width": z.number().int().nullable().optional(),
  "techRecord_euVehicleCategory": z.union([EUvehiclecategorySchema, z.null()]).optional(),
  "techRecord_firstUseDate": z.string().nullable().optional(),
  "techRecord_frameDescription": z.union([FrameDescriptionSchema, z.null()]).optional(),
  "techRecord_frontAxleToRearAxle": z.number().int().nullable().optional(),
  "techRecord_functionCode": z.string().nullable().optional(),
  "techRecord_grossDesignWeight": z.number().int().nullable().optional(),
  "techRecord_grossEecWeight": z.number().int().nullable().optional(),
  "techRecord_grossGbWeight": z.number().int().nullable().optional(),
  "techRecord_letterOfAuth_letterType": z.union([z.null(), lettertypesSchema]).optional(),
  "techRecord_letterOfAuth_letterDateRequested": z.string().nullable().optional(),
  "techRecord_letterOfAuth_paragraphId": z.union([z.null(), ParagraphIdsSchema]).optional(),
  "techRecord_letterOfAuth_letterIssuer": z.string().nullable().optional(),
  "techRecord_make": z.string().nullable().optional(),
  "techRecord_manufactureMonth": z.union([MonthsSchema, z.null()]).optional(),
  "techRecord_manufactureYear": z.union([z.number().int(), z.null()]).optional(),
  "techRecord_manufacturerDetails": z.string().nullable().optional(),
  "techRecord_maxLoadOnCoupling": z.number().int().nullable().optional(),
  "techRecord_microfilm": z.string().nullable().optional(),
  "techRecord_microfilm_microfilmDocumentType": z.union([z.null(), MicrofilmDocumentTypeSchema]).optional(),
  "techRecord_microfilm_microfilmRollNumber": z.string().nullable().optional(),
  "techRecord_microfilm_microfilmSerialNumber": z.string().nullable().optional(),
  "techRecord_model": z.string().nullable().optional(),
  "techRecord_axles": z.array(z.object({
  "parkingBrakeMrk": z.boolean().nullable().optional(),
  "axleNumber": z.number().int().nullable().optional(),
  "brakes_brakeActuator": z.number().int().nullable().optional(),
  "brakes_leverLength": z.number().int().nullable().optional(),
  "brakes_springBrakeParking": z.boolean().nullable().optional(),
  "weights_gbWeight": z.number().int().nullable().optional(),
  "weights_designWeight": z.number().int().nullable().optional(),
  "weights_eecWeight": z.number().int().nullable().optional(),
  "weights_ladenWeight": z.number().int().nullable().optional(),
  "weights_kerbWeight": z.number().int().nullable().optional(),
  "tyres_tyreCode": z.number().int().nullable().optional(),
  "tyres_tyreSize": z.string().nullable().optional(),
  "tyres_plyRating": z.string().nullable().optional(),
  "tyres_fitmentCode": z.union([z.null(), FitmentCodeSchema]).optional(),
  "tyres_dataTrAxles": z.number().int().nullable().optional(),
  "tyres_speedCategorySymbol": z.union([SpeedCategorySymbolSchema, z.null()]).optional(),
}).strict()).nullable().optional(),
  "techRecord_noOfAxles": z.union([z.number().int(), z.null()]).optional(),
  "techRecord_plates": z.array(z.object({
  "plateSerialNumber": z.string().nullable().optional(),
  "plateIssueDate": z.string().nullable().optional(),
  "plateReasonForIssue": z.union([z.null(), PlateReasonForIssueSchema]).optional(),
  "plateIssuer": z.string().nullable().optional(),
}).strict()).nullable().optional(),
  "techRecord_purchaserDetails_address1": z.string().nullable().optional(),
  "techRecord_purchaserDetails_address2": z.string().nullable().optional(),
  "techRecord_purchaserDetails_address3": z.string().nullable().optional(),
  "techRecord_purchaserDetails_emailAddress": z.string().nullable().optional(),
  "techRecord_purchaserDetails_faxNumber": z.string().nullable().optional(),
  "techRecord_purchaserDetails_name": z.string().nullable().optional(),
  "techRecord_purchaserDetails_postCode": z.string().nullable().optional(),
  "techRecord_purchaserDetails_postTown": z.string().nullable().optional(),
  "techRecord_purchaserDetails_purchaserNotes": z.string().nullable().optional(),
  "techRecord_purchaserDetails_telephoneNumber": z.string().nullable().optional(),
  "techRecord_manufacturerDetails_address1": z.string().nullable().optional(),
  "techRecord_manufacturerDetails_address2": z.string().nullable().optional(),
  "techRecord_manufacturerDetails_address3": z.string().nullable().optional(),
  "techRecord_manufacturerDetails_emailAddress": z.string().nullable().optional(),
  "techRecord_manufacturerDetails_faxNumber": z.string().nullable().optional(),
  "techRecord_manufacturerDetails_name": z.string().nullable().optional(),
  "techRecord_manufacturerDetails_postCode": z.string().nullable().optional(),
  "techRecord_manufacturerDetails_postTown": z.string().nullable().optional(),
  "techRecord_manufacturerDetails_manufacturerNotes": z.string().nullable().optional(),
  "techRecord_manufacturerDetails_telephoneNumber": z.string().nullable().optional(),
  "techRecord_lastUpdatedAt": z.string().nullable().optional(),
  "techRecord_lastUpdatedByName": z.string().nullable().optional(),
  "techRecord_lastUpdatedById": z.string().nullable().optional(),
  "techRecord_rearAxleToRearTrl": z.number().int().nullable().optional(),
  "techRecord_reasonForCreation": z.string(),
  "techRecord_recordCompleteness": z.literal("skeleton").optional(),
  "techRecord_regnDate": z.union([z.string().regex(new RegExp("^$")), z.string().regex(new RegExp("^\\d{4}-\\d{2}-\\d{2}$")), z.null()]).optional(),
  "techRecord_roadFriendly": z.boolean().nullable().optional(),
  "techRecord_statusCode": StatusCodeSchema,
  "techRecord_suspensionType": z.string().nullable().optional(),
  "techRecord_tyreUseCode": z.union([TyreUseCodeSchema, z.null()]).optional(),
  "techRecord_vehicleClass_code": z.literal("t"),
  "techRecord_vehicleClass_description": z.literal("trailer"),
  "techRecord_vehicleConfiguration": z.union([VehicleConfigurationSchema, z.null()]).optional(),
  "techRecord_vehicleType": z.literal("trl"),
  "trailerId": z.string(),
  "vin": z.string(),
  "techRecord_hiddenInVta": z.boolean().nullable().optional(),
  "techRecord_updateType": z.string().nullable().optional(),
  "techRecord_authIntoService_cocIssueDate": z.string().nullable().optional(),
  "techRecord_authIntoService_dateReceived": z.string().nullable().optional(),
  "techRecord_authIntoService_datePending": z.string().nullable().optional(),
  "techRecord_authIntoService_dateAuthorised": z.string().nullable().optional(),
  "techRecord_authIntoService_dateRejected": z.string().nullable().optional(),
  "techRecord_notes": z.string().nullable().optional(),
  "techRecord_dimensions_axleSpacing": z.array(z.object({
  "axles": z.string().optional(),
  "value": z.number().int().nullable().optional(),
}).strict()).optional(),
}).strict();

export type TechRecordGETTRLSkeleton = z.infer<typeof TechRecordGETTRLSkeletonSchema>;
