/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum FuelType {
  DIESEL = "diesel",
  GAS_CNG = "gas-cng",
  GAS_LNG = "gas-lng",
  GAS_LPG = "gas-lpg",
  PETROL = "petrol",
  FUEL_CELL = "fuel cell",
  FULL_ELECTRIC = "full electric"
}
