/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum LoadStatusType {
  UNLADEN = "Unladen",
  PARTIALLY_LADEN = "Partially laden",
  PARTIALLY_LADEN_50_TO_65 = "Partially laden 50% to 65%",
  FULLY_LADEN = "Fully laden",
  LOAD_SIMULATED_PARTIALLY_LADEN = "Load simulated partially laden",
  LOAD_SIMULATED_FULLY_LADEN = "Load simulated fully laden"
}
