/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum ReasonForNotLoading {
  OBNOXIOUS_LOADS = "Obnoxious loads",
  TANKER = "Tanker",
  PERISHABLE_GOODS = "Perishable goods",
  LIVESTOCK = "Livestock",
  CAR_TRANSPORTER = "Car transporter",
  REFUSE = "Refuse",
  STREET_CLEANER = "Street cleaner",
  ULTAST = "ULTAST",
  SPECIALIST_BODY_LOAD = "Specialist body/load",
  OTHER = "Other"
}
