/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum UnladenBodyType {
  SKELETAL = "Skeletal",
  CURTAIN = "Curtain",
  FRIDGE = "Fridge",
  BOX = "Box",
  TANK = "Tank",
  FLAT = "Flat",
  CAR_TRANSPORTER = "Car transporter",
  FIXED_PLANT = "Fixed plant",
  TIPPER = "Tipper",
  REFUGE = "Refuge",
  STREET_CLEANER = "Street cleaner",
  SPECIALISED_VEHICLE_TRAILER = "Specialised vehicle/trailer",
  OTHER = "Other"
}
