/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export enum WaitReason {
  WAITING_FOR_VEHICLE = "Waiting for vehicle",
  BREAK = "Break",
  ADMIN = "Admin",
  SITE_ISSUE = "Site issue",
  OTHER = "Other"
}
