// AUTO-GENERATED from json-definitions/enums/refDataType.enum.json. Do not edit by hand.

import { z } from "zod";

export enum RefDataType {
  "BRAKES" = "BRAKES",
  "COUNTRY_OF_REGISTRATION" = "COUNTRY_OF_REGISTRATION",
  "HGV_MAKE" = "HGV_MAKE",
  "PSV_MAKE" = "PSV_MAKE",
  "MSVA_REASONS_FOR_ABANDONING" = "MSVA_REASONS_FOR_ABANDONING",
  "REASONS_FOR_ABANDONING_HGV" = "REASONS_FOR_ABANDONING_HGV",
  "REASONS_FOR_ABANDONING_PSV" = "REASONS_FOR_ABANDONING_PSV",
  "REASONS_FOR_ABANDONING_TRL" = "REASONS_FOR_ABANDONING_TRL",
  "SPECIALIST_REASONS_FOR_ABANDONING" = "SPECIALIST_REASONS_FOR_ABANDONING",
  "TIR_REASONS_FOR_ABANDONING" = "TIR_REASONS_FOR_ABANDONING",
  "TRL_MAKE" = "TRL_MAKE",
  "TYRE_LOAD_INDEX" = "TYRE_LOAD_INDEX",
  "TYRES" = "TYRES",
}

export const RefDataTypeSchema = z.enum(RefDataType);
