/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type GETPSVTechnicalRecordV3Complete = Foo;
export type Foo = PSVBrakes & ApplicantDetails;
export type RetarderBrake = "electric" | "exhaust" | "friction" | "hydraulic" | "other" | "none";

export interface PSVBrakes {
  techRecord_brakes_dtpNumber?: string | null;
  techRecord_brakes_brakeCode?: string | null;
  techRecord_brakes_brakeCodeOriginal?: string | null;
  techRecord_brakes_dataTrBrakeOne?: string | null;
  techRecord_brakes_dataTrBrakeTwo?: string | null;
  techRecord_brakes_dataTrBrakeThree?: string | null;
  techRecord_brakes_retarderBrakeOne?: RetarderBrake | null;
  techRecord_brakes_retarderBrakeTwo?: RetarderBrake | null;
  techRecord_brakes_brakeForceWheelsNotLocked_parkingBrakeForceA?: number | null;
  techRecord_brakes_brakeForceWheelsNotLocked_secondaryBrakeForceA?: number | null;
  techRecord_brakes_brakeForceWheelsNotLocked_serviceBrakeForceA?: number | null;
  techRecord_brakes_brakeForceWheelsUpToHalfLocked_parkingBrakeForceB?: number | null;
  techRecord_brakes_brakeForceWheelsUpToHalfLocked_secondaryBrakeForceB?: number | null;
  techRecord_brakes_brakeForceWheelsUpToHalfLocked_serviceBrakeForceB?: number | null;
}
export interface ApplicantDetails {
  techRecord_applicantDetails_name?: string | null;
  techRecord_applicantDetails_address1?: null | string;
  techRecord_applicantDetails_address2?: null | string;
  techRecord_applicantDetails_postTown?: null | string;
  techRecord_applicantDetails_address3?: null | string;
  techRecord_applicantDetails_postCode?: null | string;
  techRecord_applicantDetails_telephoneNumber?: null | string;
  techRecord_applicantDetails_emailAddress?: null | string;
}
