/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StatusCode = "provisional" | "current" | "archived";

export interface TechRecordSearchSchema {
  primaryVrm?: string;
  vin: string;
  techRecord_statusCode: StatusCode;
  techRecord_vehicleType: VehicleType;
  createdTimestamp: string;
  trailerId?: string;
  systemNumber: string;
  techRecord_chassisMake?: null | string;
  techRecord_chassisModel?: null | string;
  techRecord_make?: null | string;
  techRecord_model?: null | string;
  techRecord_manufactureYear: number | null;
  techRecord_reasonForCreation?: string;
  techRecord_createdByName?: string;
}

export enum VehicleType {
  psv = "psv",
  trl = "trl",
  hgv = "hgv",
  car = "car",
  lgv = "lgv",
  motorcycle = "motorcycle"
}
