/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type InspectionType = "basic" | "normal";

export interface RequiredStandardTaxonomySection {
  sectionNumber: string;
  sectionDescription: string;
  requiredStandards: RequiredStandard[];
}
export interface RequiredStandard {
  rsNumber: number;
  requiredStandard: string;
  refCalculation: string;
  additionalInfo: boolean;
  inspectionTypes: InspectionType[];
}
