/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AxleSchema {
  parkingBrakeMrk?: boolean;
  axleNumber: number;
  weights?: WeightsSchema;
  tyres: TyresSchema;
  brakes?: AxleBrakePropertiesSchema;
}
export interface WeightsSchema {
  kerbWeight?: number;
  ladenWeight?: number;
  gbWeight: number;
  designWeight: number;
}
export interface TyresSchema {
  tyreSize: string;
  plyRating: string;
  fitmentCode: string;
  dataTrPsvAxles?: number;
  tyreCode: number;
  dataTrAxles?: number;
  /**
   * PSV only
   */
  speedCategorySymbol?: string;
}
export interface AxleBrakePropertiesSchema {
  brakeActuator: number;
  leverLength: number;
  springBrakeParking: boolean;
}
