// AUTO-GENERATED from json-definitions/v3/tech-record/put/hgv/complete/index.json. Do not edit by hand.

import { z } from "zod";

import { ADRBodyDeclarationTypesSchema } from "./../../../enums/adrBodyDeclarationType.enum";
import { RadioButtonOptionsSchema } from "./../../../enums/radioButtonOptions.enum";
import { ADRCompatibilityGroupJSchema } from "./../../../enums/adrCompatibilityGroupJ.enum";
import { TC2TypesSchema } from "./../../../enums/tc2Types.ignore";
import { TC3TypesSchema } from "./../../../enums/tc3Types.enum";
import { ADRTankDetailsTankStatementSelectSchema } from "./../../../enums/adrTankDetailsTankStatementSelect.enum";
import { ADRCertificateTypesSchema } from "./../../../enums/adrCertificateTypes.enum";
import { FitmentCodeSchema } from "./../../../enums/fitmentCode.ignore";
import { EUVehicleCategorySchema } from "./../../../enums/euVehicleCategoryHgv.enum";
import { FuelPropulsionSystemSchema } from "./../../../enums/fuelPropulsionSystem.ignore";
import { MicrofilmDocumentTypeSchema } from "./../../../enums/microfilmDocumentType.ignore";
import { PlateReasonForIssueSchema } from "./../../../enums/plateReasonForIssue.ignore";
import { StatusCodeSchema } from "./../../../enums/statusCode.ignore";
import { TyreUseCodeSchema } from "./../../../enums/tyreUseCodeHgv.enum";
import { VehicleConfigurationSchema } from "./../../../enums/vehicleConfigurationHgvPsv.enum";
import { ApprovalTypeSchema } from "./../../../enums/approvalTypeHgvOrPsv.enum";

export const TechRecordPUTHGVCompleteSchema = z.object({
  "secondaryVrms": z.array(z.string()).optional(),
  "partialVin": z.string().nullable().optional(),
  "techRecord_adrDetails_documentId": z.string().optional(),
  "techRecord_adrDetails_dangerousGoods": z.boolean().nullable().optional(),
  "techRecord_adrDetails_vehicleDetails_type": z.string().nullable().optional(),
  "techRecord_adrDetails_bodyDeclaration_type": z.union([z.null(), ADRBodyDeclarationTypesSchema]).optional(),
  "techRecord_adrDetails_vehicleDetails_usedOnInternationalJourneys": z.union([z.null(), RadioButtonOptionsSchema]).optional(),
  "techRecord_adrDetails_vehicleDetails_approvalDate": z.union([z.string().regex(new RegExp("^\\d{4}-\\d{2}-\\d{2}$")), z.null()]).optional(),
  "techRecord_adrDetails_permittedDangerousGoods": z.array(z.string()).nullable().optional(),
  "techRecord_adrDetails_compatibilityGroupJ": z.union([z.null(), ADRCompatibilityGroupJSchema]).optional(),
  "techRecord_adrDetails_additionalExaminerNotes": z.array(z.object({
  "note": z.string().nullable().optional(),
  "createdAtDate": z.string().nullable().optional(),
  "lastUpdatedBy": z.string().nullable().optional(),
}).strict()).nullable().optional(),
  "techRecord_adrDetails_applicantDetails_name": z.string().nullable().optional(),
  "techRecord_adrDetails_applicantDetails_street": z.string().nullable().optional(),
  "techRecord_adrDetails_applicantDetails_town": z.string().nullable().optional(),
  "techRecord_adrDetails_applicantDetails_city": z.string().nullable().optional(),
  "techRecord_adrDetails_applicantDetails_postcode": z.string().nullable().optional(),
  "techRecord_adrDetails_memosApply": z.array(z.string()).nullable().optional(),
  "techRecord_adrDetails_documents": z.array(z.string()).nullable().optional(),
  "techRecord_adrDetails_listStatementApplicable": z.boolean().nullable().optional(),
  "techRecord_adrDetails_batteryListNumber": z.string().nullable().optional(),
  "techRecord_adrDetails_brakeDeclarationsSeen": z.boolean().nullable().optional(),
  "techRecord_adrDetails_brakeDeclarationIssuer": z.string().nullable().optional(),
  "techRecord_adrDetails_brakeEndurance": z.boolean().nullable().optional(),
  "techRecord_adrDetails_weight": z.number().nullable().optional(),
  "techRecord_adrDetails_declarationsSeen": z.boolean().nullable().optional(),
  "techRecord_adrDetails_m145Statement": z.boolean().nullable().optional(),
  "techRecord_adrDetails_newCertificateRequested": z.boolean().nullable().optional(),
  "techRecord_adrDetails_additionalNotes_number": z.array(z.string()).nullable().optional(),
  "techRecord_adrDetails_adrTypeApprovalNo": z.string().nullable().optional(),
  "techRecord_adrDetails_adrCertificateNotes": z.string().nullable().optional(),
  "techRecord_adrDetails_approved": z.boolean().nullable().optional(),
  "techRecord_adrDetails_receivedDate": z.union([z.string().regex(new RegExp("^\\d{4}-\\d{2}-\\d{2}$")), z.null()]).optional(),
  "techRecord_adrDetails_applicationNumber": z.union([z.string().regex(new RegExp("^APP-\\d{7}-\\d{4}-\\d{1,2}$")), z.null()]).optional(),
  "techRecord_adrDetails_tank_tankDetails_tankManufacturer": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_yearOfManufacture": z.number().int().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankManufacturerSerialNo": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankTypeAppNo": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankCode": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_specialProvisions": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tc2Details_tc2Type": z.union([z.null(), TC2TypesSchema]).optional(),
  "techRecord_adrDetails_tank_tankDetails_tc2Details_tc2IntermediateApprovalNo": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tc2Details_tc2IntermediateExpiryDate": z.union([z.string().regex(new RegExp("^\\d{4}-\\d{2}-\\d{2}$")), z.null()]).optional(),
  "techRecord_adrDetails_tank_tankDetails_tc3Details": z.array(z.object({
  "tc3Type": z.union([z.null(), TC3TypesSchema]).optional(),
  "tc3PeriodicNumber": z.string().nullable().optional(),
  "tc3PeriodicExpiryDate": z.union([z.string().regex(new RegExp("^\\d{4}-\\d{2}-\\d{2}$")), z.null()]).optional(),
}).strict()).nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankStatement_substancesPermitted": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankStatement_select": z.union([z.null(), ADRTankDetailsTankStatementSelectSchema]).optional(),
  "techRecord_adrDetails_tank_tankDetails_tankStatement_statement": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankStatement_productListRefNo": z.string().nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankStatement_productListUnNo": z.array(z.string()).nullable().optional(),
  "techRecord_adrDetails_tank_tankDetails_tankStatement_productList": z.string().nullable().optional(),
  "techRecord_alterationMarker": z.boolean().nullable().optional(),
  "techRecord_adrPassCertificateDetails": z.array(z.object({
  "createdByName": z.string(),
  "certificateType": ADRCertificateTypesSchema,
  "generatedTimestamp": z.string(),
  "certificateId": z.string(),
}).strict()).nullable().optional(),
  "techRecord_applicantDetails_name": z.string(),
  "techRecord_applicantDetails_address1": z.string(),
  "techRecord_applicantDetails_address2": z.string(),
  "techRecord_applicantDetails_postTown": z.string(),
  "techRecord_applicantDetails_address3": z.string().nullable().optional(),
  "techRecord_applicantDetails_postCode": z.string().nullable().optional(),
  "techRecord_applicantDetails_telephoneNumber": z.string().nullable().optional(),
  "techRecord_applicantDetails_emailAddress": z.string().nullable().optional(),
  "techRecord_applicationId": z.string().nullable().optional(),
  "techRecord_axles": z.array(z.object({
  "parkingBrakeMrk": z.boolean().optional(),
  "axleNumber": z.number().int().optional(),
  "weights_gbWeight": z.number().int(),
  "weights_designWeight": z.number().int(),
  "weights_eecWeight": z.number().int().nullable().optional(),
  "tyres_tyreCode": z.number().int(),
  "tyres_tyreSize": z.string(),
  "tyres_plyRating": z.string().nullable().optional(),
  "tyres_fitmentCode": FitmentCodeSchema,
  "tyres_dataTrAxles": z.number().int().nullable().optional(),
}).strict()),
  "techRecord_bodyType_code": z.string(),
  "techRecord_bodyType_description": z.string(),
  "techRecord_brakes_dtpNumber": z.string(),
  "techRecord_brakes_loadSensingValve": z.boolean().nullable().optional(),
  "techRecord_conversionRefNo": z.string().nullable().optional(),
  "techRecord_departmentalVehicleMarker": z.boolean().nullable().optional(),
  "techRecord_dimensions_axleSpacing": z.array(z.object({
  "axles": z.string().optional(),
  "value": z.number().int().nullable().optional(),
}).strict()).optional(),
  "techRecord_dimensions_length": z.number().int(),
  "techRecord_dimensions_width": z.number().int(),
  "techRecord_drawbarCouplingFitted": z.boolean(),
  "techRecord_emissionsLimit": z.number().nullable().optional(),
  "techRecord_euroStandard": z.string(),
  "techRecord_euVehicleCategory": EUVehicleCategorySchema,
  "techRecord_frontAxleToRearAxle": z.number().int(),
  "techRecord_frontAxleTo5thWheelMin": z.number().int(),
  "techRecord_frontAxleTo5thWheelMax": z.number().int(),
  "techRecord_frontVehicleTo5thWheelCouplingMin": z.number().int().nullable().optional(),
  "techRecord_frontVehicleTo5thWheelCouplingMax": z.number().int().nullable().optional(),
  "techRecord_fuelPropulsionSystem": FuelPropulsionSystemSchema,
  "techRecord_functionCode": z.string().nullable().optional(),
  "techRecord_grossDesignWeight": z.number().int(),
  "techRecord_grossEecWeight": z.number().int().nullable().optional(),
  "techRecord_grossGbWeight": z.number().int(),
  "techRecord_make": z.string(),
  "techRecord_maxTrainGbWeight": z.number(),
  "techRecord_maxTrainEecWeight": z.number().nullable().optional(),
  "techRecord_maxTrainDesignWeight": z.number().nullable().optional(),
  "techRecord_manufactureYear": z.number().int(),
  "techRecord_microfilm_microfilmDocumentType": z.union([z.null(), MicrofilmDocumentTypeSchema]).optional(),
  "techRecord_microfilm_microfilmRollNumber": z.string().nullable().optional(),
  "techRecord_microfilm_microfilmSerialNumber": z.string().nullable().optional(),
  "techRecord_model": z.string(),
  "techRecord_noOfAxles": z.union([z.number().int(), z.null()]).optional(),
  "techRecord_notes": z.string(),
  "techRecord_offRoad": z.boolean(),
  "techRecord_plates": z.array(z.object({
  "plateSerialNumber": z.string().nullable().optional(),
  "plateIssueDate": z.string().nullable().optional(),
  "plateReasonForIssue": z.union([z.null(), PlateReasonForIssueSchema]).optional(),
  "plateIssuer": z.string().nullable().optional(),
}).strict()).nullable().optional(),
  "techRecord_reasonForCreation": z.string(),
  "techRecord_regnDate": z.union([z.string().regex(new RegExp("^$")), z.string().regex(new RegExp("^\\d{4}-\\d{2}-\\d{2}$"))]),
  "techRecord_roadFriendly": z.boolean(),
  "techRecord_statusCode": StatusCodeSchema,
  "techRecord_speedLimiterMrk": z.boolean(),
  "techRecord_tachoExemptMrk": z.boolean(),
  "techRecord_trainDesignWeight": z.number().int().nullable().optional(),
  "techRecord_trainEecWeight": z.number().nullable().optional(),
  "techRecord_trainGbWeight": z.number(),
  "techRecord_tyreUseCode": TyreUseCodeSchema,
  "techRecord_vehicleClass_description": z.literal("heavy goods vehicle"),
  "techRecord_vehicleConfiguration": VehicleConfigurationSchema,
  "techRecord_approvalType": ApprovalTypeSchema,
  "techRecord_approvalTypeNumber": z.string().nullable().optional(),
  "techRecord_ntaNumber": z.string().nullable().optional(),
  "techRecord_variantNumber": z.string().nullable().optional(),
  "techRecord_variantVersionNumber": z.string().nullable().optional(),
  "techRecord_vehicleType": z.literal("hgv"),
  "primaryVrm": z.string().nullable().optional(),
  "vin": z.string(),
  "techRecord_hiddenInVta": z.boolean().nullable().optional(),
  "techRecord_updateType": z.string().nullable().optional(),
}).strict();

export type TechRecordPUTHGVComplete = z.infer<typeof TechRecordPUTHGVCompleteSchema>;
