/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TestStationSchema {
  testStationId: string;
  testStationPNumber: string;
  testStationName: string;
  testStationContactNumber: string;
  testStationAccessNotes: string;
  testStationGeneralNotes: string;
  testStationTown: string;
  testStationAddress: string;
  testStationPostcode: string;
  testStationLongitude: number;
  testStationLatitude: number;
  testStationType: string;
  testStationEmails: string[];
  searchProperty?: string;
}
