/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type VehicleType = "psv" | "trl" | "hgv" | "car" | "lgv" | "motorcycle";
export type StatusCode = "provisional" | "current" | "archived";

export interface TechRecordPUTRequestSkeletonCarSchema {
  vin: string;
  primaryVrm?: null | string;
  trailerId?: string | null;
  techRecord_reasonForCreation?: string | null;
  techRecord_vehicleType: VehicleType;
  techRecord_statusCode?: null | StatusCode;
  techRecord_regnDate?: string | null;
  techRecord_manufactureYear?: string | null;
  techRecord_noOfAxles?: number | null;
  techRecord_notes?: null | string;
  techRecord_hiddenInVta?: null | boolean;
  techRecord_updateType?: null | string;
  techRecord_createdAt?: null | string;
  techRecord_createdById?: null | string;
  techRecord_createdByName?: null | string;
  secondaryVrms?: null | string[];
}
