/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StatusCode = "provisional" | "current" | "archived";
export type VehicleSubclass = ("n" | "p" | "a" | "s" | "c" | "l" | "t" | "e" | "m" | "r" | "w")[];

export interface TechRecordPUTCarSkeleton {
  vin: string;
  primaryVrm?: null | string;
  trailerId?: string | null;
  techRecord_reasonForCreation?: string | null;
  techRecord_vehicleType: "car";
  techRecord_statusCode?: null | StatusCode;
  techRecord_regnDate?: string | null;
  techRecord_manufactureYear?: number | null;
  techRecord_noOfAxles?: number | null;
  techRecord_notes?: null | string;
  techRecord_hiddenInVta?: null | boolean;
  techRecord_updateType?: null | string;
  secondaryVrms?: null | string[];
  techRecord_vehicleSubclass?: VehicleSubclass;
}
