"use strict";
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApprovalType = void 0;
var ApprovalType;
(function (ApprovalType) {
    ApprovalType["NTA"] = "NTA";
    ApprovalType["ECTA"] = "ECTA";
    ApprovalType["IVA"] = "IVA";
    ApprovalType["NSSTA"] = "NSSTA";
    ApprovalType["ECSSTA"] = "ECSSTA";
    ApprovalType["GB_WVTA"] = "GB WVTA";
    ApprovalType["UKNI_WVTA"] = "UKNI WVTA";
    ApprovalType["EU_WVTA_PRE_23"] = "EU WVTA Pre 23";
    ApprovalType["EU_WVTA_23_ON"] = "EU WVTA 23 on";
    ApprovalType["QNIG"] = "QNIG";
    ApprovalType["PROV_GB_WVTA"] = "Prov.GB WVTA";
    ApprovalType["SMALL_SERIES_NKSXX"] = "Small series NKSXX";
    ApprovalType["SMALL_SERIES_NKS"] = "Small series NKS";
    ApprovalType["IVA_VCA"] = "IVA - VCA";
    ApprovalType["IVA_DVSA_NI"] = "IVA - DVSA/NI";
})(ApprovalType = exports.ApprovalType || (exports.ApprovalType = {}));
