/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare enum ApprovalType {
    NTA = "NTA",
    ECTA = "ECTA",
    IVA = "IVA",
    NSSTA = "NSSTA",
    ECSSTA = "ECSSTA",
    GB_WVTA = "GB WVTA",
    PROV_GB_WVTA = "Prov.GB WVTA",
    SMALL_SERIES_NKSXX = "Small series NKSXX",
    SMALL_SERIES_NKS = "Small series NKS",
    IVA_VCA = "IVA - VCA",
    IVA_DVSA_NI = "IVA - DVSA/NI"
}
