"use strict";
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EUVehicleCategory = void 0;
var EUVehicleCategory;
(function (EUVehicleCategory) {
    EUVehicleCategory["N1"] = "n1";
    EUVehicleCategory["N2"] = "n2";
    EUVehicleCategory["N3"] = "n3";
})(EUVehicleCategory = exports.EUVehicleCategory || (exports.EUVehicleCategory = {}));
