"use strict";
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EUVehicleCategory = void 0;
var EUVehicleCategory;
(function (EUVehicleCategory) {
    EUVehicleCategory["M1"] = "m1";
    EUVehicleCategory["M2"] = "m2";
    EUVehicleCategory["M3"] = "m3";
    EUVehicleCategory["N1"] = "n1";
    EUVehicleCategory["N2"] = "n2";
    EUVehicleCategory["N3"] = "n3";
    EUVehicleCategory["O1"] = "o1";
    EUVehicleCategory["O2"] = "o2";
    EUVehicleCategory["O3"] = "o3";
    EUVehicleCategory["O4"] = "o4";
    EUVehicleCategory["L1E_A"] = "l1e-a";
    EUVehicleCategory["l1E"] = "l1e";
    EUVehicleCategory["L2e"] = "l2e";
    EUVehicleCategory["L3E"] = "l3e";
    EUVehicleCategory["L4E"] = "l4e";
    EUVehicleCategory["L5E"] = "l5e";
    EUVehicleCategory["L6E"] = "l6e";
    EUVehicleCategory["L7E"] = "l7e";
})(EUVehicleCategory = exports.EUVehicleCategory || (exports.EUVehicleCategory = {}));
