/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare enum EUVehicleCategory {
    M1 = "m1",
    M2 = "m2",
    M3 = "m3"
}
