"use strict";
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EUVehicleCategory = void 0;
var EUVehicleCategory;
(function (EUVehicleCategory) {
    EUVehicleCategory["M1"] = "m1";
    EUVehicleCategory["M2"] = "m2";
    EUVehicleCategory["M3"] = "m3";
})(EUVehicleCategory = exports.EUVehicleCategory || (exports.EUVehicleCategory = {}));
