"use strict";
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VehicleClassDescription = void 0;
var VehicleClassDescription;
(function (VehicleClassDescription) {
    VehicleClassDescription["SMALL_PSV"] = "small psv (ie: less than or equal to 22 seats)";
    VehicleClassDescription["LARGE_PSV"] = "large psv(ie: greater than 23 seats)";
})(VehicleClassDescription = exports.VehicleClassDescription || (exports.VehicleClassDescription = {}));
