"use strict";
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VehicleClassDescription = void 0;
var VehicleClassDescription;
(function (VehicleClassDescription) {
    VehicleClassDescription["MotorbikesOver200ccOrWithASidecar"] = "motorbikes over 200cc or with a sidecar";
    VehicleClassDescription["NotApplicable"] = "not applicable";
    VehicleClassDescription["SmallPsvIeLessThanOrEqualTo22Seats"] = "small psv (ie: less than or equal to 22 seats)";
    VehicleClassDescription["MotorbikesUpTo200cc"] = "motorbikes up to 200cc";
    VehicleClassDescription["Trailer"] = "trailer";
    VehicleClassDescription["LargePsvIeGreaterThan23Seats"] = "large psv(ie: greater than 23 seats)";
    VehicleClassDescription["_3Wheelers"] = "3 wheelers";
    VehicleClassDescription["HeavyGoodsVehicle"] = "heavy goods vehicle";
    VehicleClassDescription["MOTClass4"] = "MOT class 4";
    VehicleClassDescription["MOTClass7"] = "MOT class 7";
    VehicleClassDescription["MOTClass5"] = "MOT class 5";
})(VehicleClassDescription = exports.VehicleClassDescription || (exports.VehicleClassDescription = {}));
