"use strict";
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VehicleConfiguration = void 0;
var VehicleConfiguration;
(function (VehicleConfiguration) {
    VehicleConfiguration["CENTRE_AXLE_DRAWBAR"] = "centre axle drawbar";
    VehicleConfiguration["SEMI_CAR_TRANSPORTER"] = "semi-car transporter";
    VehicleConfiguration["SEMI_TRAILER"] = "semi-trailer";
    VehicleConfiguration["LONG_SEMI_TRAILER"] = "long semi-trailer";
    VehicleConfiguration["LOW_LOADER"] = "low loader";
    VehicleConfiguration["OTHER"] = "other";
    VehicleConfiguration["DRAWBAR"] = "drawbar";
    VehicleConfiguration["FOUR_IN_LINE"] = "four-in-line";
    VehicleConfiguration["DOLLY"] = "dolly";
    VehicleConfiguration["FULL_DRAWBAR"] = "full drawbar";
})(VehicleConfiguration = exports.VehicleConfiguration || (exports.VehicleConfiguration = {}));
