/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type VehicleType = "psv" | "trl" | "hgv" | "car" | "lgv" | "motorcycle";
export type EUVehicleCategory =
  | "m1"
  | "m2"
  | "m3"
  | "n1"
  | "n2"
  | "n3"
  | "o1"
  | "o2"
  | "o3"
  | "o4"
  | "l1e-a"
  | "l1e"
  | "l2e"
  | "l3e"
  | "l4e"
  | "l5e"
  | "l6e"
  | "l7e";
export type InspectionType = "basic" | "normal";

export interface DefectGETIVA {
  sectionNumber: string;
  sectionDescription: string;
  vehicleTypes: VehicleType;
  euVehicleCategories: EUVehicleCategory;
  requiredStandards: {
    rsNumber: number;
    requiredStandard: string;
    refCalculation: string;
    additionalInfo: boolean;
    inspectionTypes: InspectionType;
    [k: string]: unknown;
  }[];
}
