/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StatusCode = "provisional" | "current" | "archived";
export type VehicleClassDescription =
  | "motorbikes over 200cc or with a sidecar"
  | "not applicable"
  | "small psv (ie: less than or equal to 22 seats)"
  | "motorbikes up to 200cc"
  | "trailer"
  | "large psv(ie: greater than 23 seats)"
  | "3 wheelers"
  | "heavy goods vehicle"
  | "MOT class 4"
  | "MOT class 7"
  | "MOT class 5";
export type VehicleSubclass = ("n" | "p" | "a" | "s" | "c" | "l" | "t" | "e" | "m" | "r" | "w")[];

export interface TechRecordPUTSmallTRLSkeleton {
  techRecord_applicantDetails_address1?: string | null;
  techRecord_applicantDetails_address2?: string | null;
  techRecord_applicantDetails_address3?: string | null;
  techRecord_applicantDetails_emailAddress?: string | null;
  techRecord_applicantDetails_name?: string | null;
  techRecord_applicantDetails_postCode?: string | null;
  techRecord_applicantDetails_postTown?: string | null;
  techRecord_applicantDetails_telephoneNumber?: string | null;
  techRecord_euVehicleCategory: "o1" | "o2";
  techRecord_manufactureYear?: number | null;
  techRecord_noOfAxles?: number | null;
  techRecord_notes?: string | null;
  techRecord_reasonForCreation: string;
  techRecord_statusCode: StatusCode;
  techRecord_vehicleClass_description: VehicleClassDescription;
  techRecord_vehicleConfiguration?: null | VehicleConfiguration;
  techRecord_vehicleSubclass?: VehicleSubclass;
  techRecord_vehicleType: "trl";
  vin: string;
  trailerId?: string;
  techRecord_hiddenInVta?: null | boolean;
}

export enum VehicleConfiguration {
  RIGID = "rigid",
  ARTICULATED = "articulated",
  CENTRE_AXLE_DRAWBAR = "centre axle drawbar",
  SEMI_CAR_TRANSPORTER = "semi-car transporter",
  SEMI_TRAILER = "semi-trailer",
  LONG_SEMI_TRAILER = "long semi-trailer",
  LOW_LOADER = "low loader",
  OTHER = "other",
  DRAWBAR = "drawbar",
  FOUR_IN_LINE = "four-in-line",
  DOLLY = "dolly",
  FULL_DRAWBAR = "full drawbar"
}
