# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PR-checks

on:
  pull_request:
    branches: ["develop"]

jobs:
  test-and-generate-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Check generate
        run: |
          npm run generate
          git add -N .
          git diff -s --exit-code || (echo -e "Found changes after generating files. Run \e[31mnpm run generate\e[0m, and push the changes to the branch." && exit 1)
      - name: Check PR title
        uses: actions/github-script@v6
        with:
          script: |
            const semVarVersions = ["patch", "minor", "major"]
            const prTitleVersion = context.payload.pull_request.title.split("(")[0]
            if (!semVarVersions.includes(prTitleVersion)) {
              throw new Error("Rename PR in the format: path|minor|major(ticket-number): description")
            }
