name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force deploy'
        default: false
        type: boolean
  workflow_run:
    workflows: ["Create Release"]
    types: [completed]
    
permissions:
  id-token: write   # Required for OIDC
  contents: read
  
jobs:
  push-to-npm:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.inputs.force }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Update npm to latest version for OIDC support
        run: npm install -g npm@latest
          
      - name: Install packages
        run: npm ci
        
      - name: Build package
        run: npm run build
        
      - name: Package files
        run: |
          cp -r types lib
          
      - name: Publish on npm
        run: cd lib && npm publish --provenance --access public
